import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import {WavyBackground} from "@/components/wavy-background";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nimesh's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body>
        <div className="fixed inset-0 z-[-1] pointer-events-none">
          <WavyBackground />
        </div>

        <Header />
        {/* Main content container starts below the header */}
        <main className="pt-36 px-6"> 
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
